//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttendance
    {
        public int AttendanceId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
    
        public virtual tblMembership tblMembership { get; set; }
    }
}
