//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeasurement
    {
        public int MeasurementId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Chest { get; set; }
        public Nullable<decimal> Weist { get; set; }
        public Nullable<decimal> Hip { get; set; }
        public Nullable<decimal> Thigh { get; set; }
        public Nullable<decimal> Bicep { get; set; }
        public Nullable<decimal> Forearm { get; set; }
        public Nullable<System.DateTime> MeasurementDate { get; set; }
    
        public virtual tblMembership tblMembership { get; set; }
    }
}
