//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShift
    {
        public tblShift()
        {
            this.tblMemberships = new HashSet<tblMembership>();
        }
    
        public int ShiftId { get; set; }
        public string ShiftName { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
    
        public virtual ICollection<tblMembership> tblMemberships { get; set; }
    }
}
