//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkout
    {
        public int WorkoutId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string WorkoutDays { get; set; }
        public string Description { get; set; }
    
        public virtual tblMembership tblMembership { get; set; }
    }
}
